basePath: /apis/blogs/v1
definitions:
  controllers.ControllerError:
    additionalProperties: true
    type: object
  controllers.ServiceStatus:
    properties:
      errors:
        items:
          type: string
        type: array
      status:
        additionalProperties:
          type: boolean
        type: object
      version:
        type: string
    type: object
  models.Blog:
    properties:
      domain:
        description: Domain is the domain name where this blog lives on the internet.
        type: string
      name:
        description: Name is the title of the blog.
        type: string
    type: object
host: https://the-hawk.us
info:
  contact:
    email: robert@the-hawk.us
    name: Robert Hawk
  description: UPDATE DESCRIPTION FIELD
  title: THUS Blogs Backend
  version: 0.1.0+0
paths:
  /health:
    get:
      description: |-
        Healthcheck endpoint. Reports which statuses are currently
        running and the current API\'s version number. If critical
        services are running, it will return 200. If any of the
        critical services are down, then the endpoint will return 503.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ServiceStatus'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/controllers.ServiceStatus'
      summary: Check to assure that the service is running.
  /sites:
    get:
      description: Lists all blogs that are managed by this backend. Authentication
        is required to use this endpoint.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Blog'
            type: array
        "204":
          description: No Content
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ControllerError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ControllerError'
      summary: List all blog sites managed by this backend.
    post:
      description: Creates a new blog site to be managed by this backend. Authentication
        is required to use this endpoint.
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Blog'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ControllerError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controllers.ControllerError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ControllerError'
      summary: Create a new blog site.
  /sites/{blog_domain}:
    delete:
      description: |-
        Performs a hard delete on this blog and all posts belonging to this blog. Since this is a hard delete
        this ACTION CAN NOT BE UNDONE! Requires authentication.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Blog'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ControllerError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ControllerError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ControllerError'
      summary: Delete the specified blog from this backend.
    put:
      description: This endpoint is used to update the name or domain name of a managed
        blog. Authentication is required.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Blog'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ControllerError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ControllerError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controllers.ControllerError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ControllerError'
      summary: Edit data pertaining to a managed blog.
swagger: "2.0"
